### ISSUE TITLE
custom weapon 

### ISSUE THREAD

**Issue by e54385991** [schwarper/cs2-store#28]
I believe it's necessary to check the settings; otherwise, it will throw an exception for those not being used

    public static void OnEntityCreated(CEntityInstance entity)
    {
        if (CoreConfig.FollowCS2ServerGuidelines)
        {
            //FollowCS2ServerGuidelines  some tips
            return;
        }
    }
```
---> System.Exception: Cannot set or get 'CEconEntity::m_OriginalOwnerXuidLow' with "FollowCS2ServerGuidelines" option enabled.
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetSchemaOffset(String className, String propertyName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 62
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetRef[T](IntPtr pointer, String className, String memberName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 110
   at CounterStrikeSharp.API.Core.CEconEntity.get_OriginalOwnerXuidLow() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CEconEntity.g.cs:line 27
   at Store.Store.<>c__DisplayClass26_0.<OnEntityCreated_CustomWeapon>b__0() in C:\Users\Enes\Desktop\cs2-store-main\Store\src\item\items\customweapon.cs:line 86
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-04-17 10:44:30.977 +08:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Cannot set or get 'CEconEntity::m_OriginalOwnerXuidLow' with "FollowCS2ServerGuidelines" option enabled.
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetSchemaOffset(String className, String propertyName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 62
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetRef[T](IntPtr pointer, String className, String memberName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 110
   at CounterStrikeSharp.API.Core.CEconEntity.get_OriginalOwnerXuidLow() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Schema/Classes/CEconEntity.g.cs:line 27
   at Store.Store.<>c__DisplayClass26_0.<OnEntityCreated_CustomWeapon>b__0() in C:\Users\Enes\Desktop\cs2-store-main\Store\src\item\items\customweapon.cs:line 86
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
```

**Comment by schwarper** [comment]
Added. If this setting is not on and there is a customweapon item, the plugin will throw exception directly.

**Comment by e54385991** [comment]
> Added. If this setting is not on and there is a customweapon item, the plugin will throw exception directly.

```
    public static void OnEntityCreated(CEntityInstance entity)
    {
        if (!entity.DesignerName.StartsWith("weapon_"))
        {
            return;
        }

        CBasePlayerWeapon weapon = entity.As<CBasePlayerWeapon>();

        Server.NextWorldUpdate(() =>
        {
            if (weapon.OriginalOwnerXuidLow == 0)
            {
                return;
            }
```
but still throw an exception  when access （weapon.OriginalOwnerXuidLow）

**Comment by schwarper** [comment]
> but still throw an exception when access （weapon.OriginalOwnerXuidLow）

Yes, i don't know why.
